version: '3.8'

services:
  backend-service-1:
    image: backend-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:8080"
  
  backend-service-2:
    image: backend-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5004:8080"

